vanillabackport\:entity.happy_ghast.ambient=true
vanillabackport\:entity.creaking.spawn=true
vanillabackport\:entity.creaking.death=true
effective\:entity.parry=true
vanillabackport\:block.eyeblossom.close=true
vanillabackport\:entity.ghastling.spawn=true
vanillabackport\:entity.happy_ghast.riding=true
vanillabackport\:entity.ghastling.death=true
vanillabackport\:entity.creaking.step=true
vanillabackport\:block.creaking_heart.hurt=true
homestead\:golden_leaf_use=true
vanillabackport\:block.creaking_heart.spawn=true
vanillabackport\:block.resin_bricks.hit=true
vanillabackport\:entity.creaking.activate=true
vanillabackport\:block.eyeblossom.open_long=true
vanillabackport\:entity.creaking.attack=true
vanillabackport\:entity.creaking.twitch=true
vanillabackport\:block.creaking_heart.hit=true
vanillabackport\:block.eyeblossom.open=true
vanillabackport\:block.resin.step=true
vanillabackport\:block.eyeblossom.close_long=true
coolrain\:rain_sounds_glass_muffled=true
vanillabackport\:block.creaking_heart.break=true
vanillabackport\:block.resin.fall=true
vanillabackport\:block.resin.break=true
coolrain\:rain_sounds_fabric_muffled=true
vanillabackport\:music_disc.tears=true
vanillabackport\:entity.happy_ghast.equip=true
vanillabackport\:music_disc.lava_chicken=true
vanillabackport\:entity.parrot.imitate.creaking=true
vanillabackport\:block.resin_bricks.step=true
vanillabackport\:block.creaking_heart.idle=true
vanillabackport\:entity.creaking.deactivate=true
vanillabackport\:block.resin.place=true
vanillabackport\:block.dried_ghast.transition=true
vanillabackport\:entity.happy_ghast.harness_goggles_down=true
vanillabackport\:block.resin_bricks.fall=true
vanillabackport\:entity.ghastling.ambient=true
vanillabackport\:block.resin_bricks.place=true
vanillabackport\:block.creaking_heart.step=true
vanillabackport\:entity.creaking.freeze=true
vanillabackport\:block.dried_ghast.fall=true
coolrain\:rain_sounds_metal_muffled=true
vanillabackport\:entity.happy_ghast.death=true
vanillabackport\:block.creaking_heart.fall=true
vanillabackport\:block.dried_ghast.ambient_water=true
vanillabackport\:block.dried_ghast.place_in_water=true
vanillabackport\:entity.ghastling.hurt=true
vanillabackport\:block.resin_bricks.break=true
vanillabackport\:block.pale_hanging_moss.idle=true
vanillabackport\:block.dried_ghast.ambient=true
keystotheend\:insert_key=true
vanillabackport\:block.dried_ghast.step=true
vanillabackport\:entity.happy_ghast.hurt=true
enhancedcelestials\:harvest_moon=true
hexalia\:conversion=true
vanillabackport\:block.creaking_heart.place=true
vanillabackport\:entity.creaking.ambient=true
vanillabackport\:entity.happy_ghast.harness_goggles_up=true
vanillabackport\:block.dried_ghast.place=true
vanillabackport\:entity.happy_ghast.unequip=true
effective\:ambience.waterfall=true
vanillabackport\:entity.creaking.unfreeze=true
enhancedcelestials\:blood_moon=true
vanillabackport\:block.dried_ghast.break=true
vanillabackport\:entity.creaking.sway=true
enhancedcelestials\:blue_moon=true
vanillabackport\:block.eyeblossom.idle=true